name: Next Snapshot Release

on:
  push:
    branches:
      - next

permissions:
  contents: write

jobs:
  next-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install deps
        run: bun install

      - name: Create snapshot versions
        run: bunx changeset version --snapshot next

      - name: Build
        run: bun run build

      - name: Publish with tag "next"
        run: bunx changeset publish --tag next
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
